# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
          cache: 'npm'
          cache-dependency-path: dashboard_description_plugin/yarn.lock
      - name: Install
        working-directory: dashboard_description_plugin
        run: |
          yarn install --frozen-lockfile
          yarn clean
          yarn build-plugin
          tar czvf dashboard-plugin.tar.gz -C dist .
      - name: Archive production artifacts
        working-directory: dashboard_description_plugin
        uses: actions/upload-artifact@v3
        with:
          name: package db plugin production build
          path: dist/dashboard-plugin.tar.gz

